### ISSUE TITLE
progress: hide does not work in mini mode

### ISSUE THREAD

**Issue by mhrono** [swiftDialog/swiftDialog#363] opened 2024-04-16 14:22 UTC
**Describe the bug**
Per [short chat in Slack](https://macadmins.slack.com/archives/C01U5MXNGG6/p1713212896518069), I've discovered that sending `progress: [ hide | remove | delete ]` to a running dialog in mini mode does not hide/remove the progress bar, and it instead remains in its last set state. Each of these keywords function as expected with a standard (not-mini) dialog.

This behavior exists in the latest dialog version as of this writing (2.4.2).

**To Reproduce**
1. Create dialog in mini mode with a command file. For consistency, the exact command used to validate this bug is:
`/usr/local/bin/dialog --mini --message "something" --progress 100 --commandfile /private/tmp/testcmd.log --moveable &`
2. Send `progress: hide` (or remove/delete) to the command file:
`echo progress: hide >> /private/tmp/testcmd.log`
3. Observe that the progress bar remains visible.
4. Repeat these steps without `--mini` in step 1, and step 2 hides the progress bar as expected.

**Expected behavior**
The progress bar should be hidden when the appropriate command is sent to a dialog's command file when using mini mode. As shown in the screenshots below, other `progress:` commands function as expected.

**Screenshots**
<img width="945" alt="image" src="https://github.com/swiftDialog/swiftDialog/assets/37225540/6f013f50-f8bc-4777-8194-e304d79fd253">
<img width="960" alt="image" src="https://github.com/swiftDialog/swiftDialog/assets/37225540/f856a3f3-cab8-4132-a3a8-b7d5724fd5c9">
<img width="959" alt="image" src="https://github.com/swiftDialog/swiftDialog/assets/37225540/c95e8d5d-80a9-48e8-be2b-fb2e5dc89c6b">

**Desktop (please complete the following information):**
 - macOS version: 14.4.1
 - swiftDialog version: 2.4.2

**Additional context**
This issue was originally identified with dialog 2.3.2. Upgrading to 2.4.2 did not resolve the issue.

**Comment by bartreardon** [comment] 2024-04-17 22:27
This is intended behaviour. The purpose of mini mode is to provide a quick progress indicator or message. It's dismissed by sending a `quit:` command when complete.

closing this as a wontfix

**Closed by bartreardon** 2024-04-17 22:27 UTC
Labels: wontfix
