### ISSUE TITLE
Long notification messages cannot be expanded

### ISSUE THREAD

**Issue by phillymjs** [swiftDialog/swiftDialog#344] opened 2024-02-08 16:25 UTC
The wiki documentation states that longer notification messages will be truncated but an ellipsis will be shown, and when the notification is moused over a chevron will appear that can be clicked to reveal the full message. In testing this behavior is not seen.

Command used to test:
~~~
dialog --notification --title "Test Notification" --message "Lorem ipsum dolor sit amit lorem ipsum dolor sit amit lorem ipsum dolor sit amit lorem ipsum dolor sit amit lorem ipsum dolor sit amit lorem ipsum dolor sit amit lorem ipsum dolor sit amit lorem ipsum dolor sit amit lorem ipsum dolor sit amit"
~~~
<br>
Expected to see an ellipsis in the notification and a chevron upon mousing over the notification.

<img width="370" alt="Screenshot 2024-02-08 at 11 19 09 AM" src="https://github.com/swiftDialog/swiftDialog/assets/5480797/def7db8a-4042-4382-bf96-6f07c673d427">

**Desktop (please complete the following information):**
 - macOS 14.3
 - swiftDialog 2.4.0.4750

**Comment by mm2270** [comment] 2024-02-15 20:24
Have you tried the latest release? 2.4.1.4754

**Comment by phillymjs** [comment] 2024-02-15 20:28
Yes, still cannot expand long messages.

**Comment by bartreardon** [comment] 2024-02-15 22:17
there's not a lot I can do about it I don't think. If you add an attachment (i.e. `--icon /some.image`) then che chevron does appear and you can see the entire text. 

I don't think the chevron has ever appears without an attachment to the notification. That's an error in the documentation on how that works and not a bug in the behaviour of notifications.

**Comment by phillymjs** [comment] 2024-02-15 22:51
Hmm, ok... I added a 1x1 transparent pixel PNG as the icon, hoping I could fudge it, but then I get this:
<img width="379" alt="Screenshot 2024-02-15 at 5 37 39 PM" src="https://github.com/swiftDialog/swiftDialog/assets/5480797/82e417a8-e4c9-4b59-8972-59b1afced830"><img width="378" alt="Screenshot 2024-02-15 at 5 37 20 PM" src="https://github.com/swiftDialog/swiftDialog/assets/5480797/ac5fd893-77fd-48e0-83f8-3f34b251bef3">

With a normal image it's clearer how it's supposed to work:

<img width="375" alt="Screenshot 2024-02-15 at 5 48 08 PM" src="https://github.com/swiftDialog/swiftDialog/assets/5480797/c18a7b90-f7cd-4d20-91eb-3e3bbc02313c">
<img width="380" alt="Screenshot 2024-02-15 at 5 44 32 PM" src="https://github.com/swiftDialog/swiftDialog/assets/5480797/c4912032-e8a6-44b2-99aa-4ba4e5fb31c5">


But then how was this screenshot on the wiki page generated, if that's the case? 🤔
![201509015-cc6591cc-5e66-4f9f-94bb-d9c0688460e9](https://github.com/swiftDialog/swiftDialog/assets/5480797/561c54f5-c00d-446c-bf7e-fdf11e735e09)

**Comment by bartreardon** [comment] 2024-02-16 02:03
older code from when I was first trying these things out - not sure what I did to make it do that but there's nothing in the docs that suggests how to replicate it - I can take a look though

**Comment by bartreardon** [comment] 2024-09-16 12:07
2.5.2 on macOS Sonoma 14.6.1 generates the following:

`dialog --notification --title "Test Notification" --message "Lorem ipsum odor amet, consectetuer adipiscing elit. Pharetra mattis accumsan elit, rhoncus convallis nascetur integer felis. Sodales cubilia ultrices et magnis mauris venenatis non dis. Odio posuere nunc orci netus netus; ipsum platea maximus ridiculus. Sit pretium ridiculus metus nisi malesuada egestas. Pharetra elementum maximus gravida felis hendrerit dapibus mattis rhoncus. Euismod natoque ipsum posuere, mauris at potenti fringilla. Pulvinar imperdiet mollis ligula nullam dignissim fames platea congue vestibulum. Vestibulum curabitur id eu placerat adipiscing sit?"`

<img width="376" alt="image" src="https://github.com/user-attachments/assets/5ab30b52-c8c2-4f44-98ec-38082fbd9f13">

At the end of the day, I'm at the whims of the macOS notification centre and how it wants to display long text. 

Closing as a wontfix, but it's more of a 'cantfix' with a bit of 'apple changes their mind and behaviour changes from version to version it seems - caveat emptor"

**Closed by bartreardon** 2024-09-16 12:07 UTC
Labels: wontfix
