### ISSUE TITLE
Small with height and width causes layout problems not present in 1.11

### ISSUE THREAD

**Issue by Lotusshaney** [swiftDialog/swiftDialog#226] opened 2023-02-03 09:20 UTC
Running the following in both v1.11.2 and v2.1.0 result in drastically differing results.

`/Library/Application\ Support/Dialog/Dialog.app/Contents/MacOS/Dialog \
    --title "Test" \
    --small \
    --height "300" \
    --width "580" \
    --iconsize "70" \
    --titlefont "size=13" \
    --messagefont "size=13" \
    --messageposition "centre" \
    --message "test message" \
    --button2`

v1.11.2 looks like this and is the required result
![Screenshot 2023-02-03 at 09 17 27](https://user-images.githubusercontent.com/1845849/216561159-4814374e-e404-4d78-9a49-a0622046ad1c.png)

v2.1.0 looks like this
![Screenshot 2023-02-03 at 09 20 00](https://user-images.githubusercontent.com/1845849/216561316-04c222c8-1a92-4f9e-9d13-d4cb6ea5d711.png)

This is on Ventura 13.2

**Comment by mm2270** [comment] 2023-02-03 16:00
I can confirm this behavior on macOS Monterey, so it's not related to macOS Ventura, in case that helps.
If I take out just the `--small` and leave all the other flags, everything shows up in the right placement, but without the desired window size.
If I remove the `--width` and `--height` flags and leave `--small`, it also works fine.

So it seems like the content within the window is not being moved inward appropriately based on the --small window flag, i.e. using width and / or height plus small aren't playing nicely with each other. I say that based on how the icon and buttons are partially, or entirely being rendered out of the window bounds.

**Comment by bartreardon** [comment] 2023-02-03 23:37
@Lotusshaney  you're suing `--small` and `--height --width` at the same time. That's not the intended use. `--small` pre-dates arbitrary `--width` and `--height` but you can think of it as a preset for displaying a smaller sized window. 

use `--small` _or_ `--width --height`

I'll consider this a bug but only in the sense that one of those options should take precedence over the other.

Using only `--width --height`:

`dialog --title "Test" --height "300" --width "580" --iconsize "70" --titlefont "size=13" --messagefont "size=13"  --messageposition "centre"  --message "test message"  --button2`

![image](https://user-images.githubusercontent.com/3598965/216730177-5388c685-0f05-4f2c-b03a-1f1078b66d6a.png)

Using only `--small`:

`dialog --title "Test"  --small --iconsize "70" --titlefont "size=13" --messagefont "size=13"  --messageposition "centre"  --message "test message"  --button2`

![image](https://user-images.githubusercontent.com/3598965/216730196-bb739405-0c40-4e3f-8b45-a251f198826a.png)

**Comment by wegotoeleven** [comment] 2023-02-06 18:43
Interesting. When using swiftDialog v1.11.2 on macOS Ventura, `small` seems to have a couple of effects on the size of the window outside of just it's width and height, as per the following:
## Defining height/width without `small`
```
displayDialog ()
{
    /usr/local/bin/dialog \
        --title "${1}" \
        --message "${2}" \
        --height "${3}" \
        --width "${4}" \
        --titlefont "size=13" \
        --messagefont "size=13" \
        --position center \
        --icon "${5}" \
        --iconsize "100"
}
displayDialog "Title" "Message" "300" "580" ""
```
![SCR-20230206-pnr](https://user-images.githubusercontent.com/7345765/217055047-7538c1ba-9c1d-4002-a6b5-9e9f6aaaaad9.png)
## Defining height/width _with_ `small`
```
displayDialog ()
{
    /usr/local/bin/dialog \
        --title "${1}" \
        --message "${2}" \
        --small \
        --height "${3}" \
        --width "${4}" \
        --titlefont "size=13" \
        --messagefont "size=13" \
        --position center \
        --icon "${5}" \
        --iconsize "100"
}
displayDialog "Title" "Message" "300" "580" ""
```
![SCR-20230206-pmb](https://user-images.githubusercontent.com/7345765/217055073-c812f228-1ae1-48d5-afa8-b2169fe3301c.png)

In the screenshots above, and the ones that @bartreardon has added, notice the height of the title bar. 

If we don't use `small`, how can we adjust the height of the title bar?

**Comment by bartreardon** [comment] 2023-08-24 00:02
closing this as a notissue

**Closed by bartreardon** 2023-08-24 00:02 UTC
Labels: notissue
