### ISSUE TITLE
ERROR: Notifications are not allowed for this application

### ISSUE THREAD

**Issue by BleakleyMcD** [swiftDialog/swiftDialog#326] opened 2024-01-04 05:08 UTC
Terminal output: 

```/Users/bleakley
≈:≈ ./Desktop/begin.sh

Folder 'JPC_AV_20240103' already exists. Not a problem!
ERROR: Notifications are not allowed for this application

Information collection canceled.
                                                                                                                                                                                                   
/Users/bleakley
≈:≈ 
```

The error is not affecting functionality of my script, but I don't know why it is appearing. It did not appear when running the script on 2.3.3 but does when running the script on 2.4.0 latest release. The only difference between the two script versions being the addition of `--background color=purple` but the error appears with or without that flag.

**Expected behavior**
I expect that error not to appear

**Desktop (please complete the following information):**
 - 12.6.9
 - 2.4.0

**Comment by bartreardon** [comment] 2024-01-04 06:00
have you deployed a notification payload as per https://github.com/swiftDialog/swiftDialog/wiki/Notifications#approving-and-setting-notification-type-via-mdm ?

**Comment by BleakleyMcD** [comment] 2024-01-04 14:38
I believe I  have any notifications in my script. Here is the dialog portion of it: 

`# Define the swiftDialog command for creating a graphical dialog`

`DIALOG_CMD="dialog --json --ontop --big --background color=#169122 --title 'JPC AV: Begin The Day' --message 'As you begin the day, please provide your name and describe your thoughts on the day ahead of you.' --textfield 'Begin The Day Thoughts,editor' --selecttitle 'Name' --selectvalues 'David Sohl, Bleakley McDowell' --selectdefault 'David Sohl' --buttonstyle center --button1text 'ONWARD!!' --button2text 'Cancel'"`

**Comment by bartreardon** [comment] 2024-01-04 21:07
you're running 2.4.0 which is a beta version, this will generate some more output than usual.

The error is being output to stderr so won't affect any data you are collecting. If it bothering you you can silence any error output by adding `2>/dev/null` to the end of your dialog command.

That said, the issue is you have notifications disabled
<img width="480" alt="image" src="https://github.com/swiftDialog/swiftDialog/assets/3598965/cb385570-73df-4fe7-af9f-401caf8b9f2e">

Usually you would set these with a notifications configuration profile or you can manually disable it in your system settings.

Closing the issue as there's nothing here that is out of the ordinary.

**Closed by bartreardon** 2024-01-04 21:07 UTC
