### ISSUE TITLE
Dialog Version 2.5 does not launch on macOS Monterey

### ISSUE THREAD

**Issue by sharristonP** [swiftDialog/swiftDialog#386] opened 2024-05-30 14:12 UTC
A mistake made by me was causing my Jamf policy to install the latest beta version of swiftDialog. In this I discovered that in swiftDialog 2.5 the window will appear for a second then disappear when run as part of a policy on a mac with Monterey installed. The issue returns and error code of:
 `/usr/local/bin/dialog: line 18: 18469 Trace/BPT trap: 5       launchctl asuser "$uid" sudo -u "$currentUser" "$@"`

I fixed my script to download the latest (non-beta) version but was asked to post this here.

**Comment by jonesiscoding** [comment] 2024-05-30 16:12
The testing machine I have been using happens to be running Monterey, and has not run into this with either Beta 3 or the RC1 versions available in releases. 

That testing machine is an Intel Mac Mini; I wonder if this is something that is only happening on Apple Silicon under Monterey.

**Comment by sharristonP** [comment] 2024-05-30 18:08
So I saw this issue on a VM on Monterey and an Intel machine on Monterey.  I was using dialog to populate a variable in a bash script if that helps as well.

**Comment by bartreardon** [comment] 2024-08-15 03:24
So doing some testing with this and I can't tell exactly when the issue is triggered however it seems to only occur if the message contains no markdown content. This behaviour is rather unusual.

Workaround at the moment is to either use a 2.4 release or make sure your message content always contains markdown

**Comment by macvfx** [comment] 2024-08-16 20:05
2.5.1-4775 beta 3 works on macOS Monterey 12.7.6. I tested it just now

**Comment by bartreardon** [comment] 2024-08-20 09:08
fixed in https://github.com/swiftDialog/swiftDialog/releases/tag/v2.5.1

**Closed by bartreardon** 2024-08-20 09:08 UTC
Labels: bug, in progress
